Repository binapani-edu/blog, pull requests merged in 2025-05, with the labels that each got.

#6 [new blog] The Journey of Social Media Evolution
  _blog.yml
  blogs/journey-of-social-media/assets/thumbnail.jpg
  blogs/journey-of-social-media/content.md
Labels: new

#15 feat(setup): add pull request template
  .github/.github/pull_request_template.md
Labels: setup

#16 feat(bot): workflows to comment blog preview link
  .github/workflows/preview-link.yml
Labels: enhancement, setup
